name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Garante variáveis no App Service (opcional, mas ajuda)
      - name: Ensure App Settings on Azure
        uses: azure/appservice-settings@v1
        with:
          app-name: surebeteiro-web
          app-settings-json: |
            [
              { "name": "NEXT_PUBLIC_SITE_URL", "value": "${{ secrets.NEXT_PUBLIC_SITE_URL }}" },
              { "name": "NEXT_PUBLIC_SUPABASE_URL", "value": "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" },
              { "name": "NEXT_PUBLIC_SUPABASE_ANON_KEY", "value": "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" },
              { "name": "WEBSITE_NODE_DEFAULT_VERSION", "value": "~20" },
              { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "1" },
              { "name": "NPM_CONFIG_PRODUCTION", "value": "false" },
              { "name": "NEXT_TELEMETRY_DISABLED", "value": "1" }
            ]

      # Deploy do código-fonte da pasta "project" (apenas 1 'package:' aqui!)
      - name: Deploy source to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: surebeteiro-web
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: project
