name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 👇 Garante que todo "run:" rode dentro de project/
    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (CI)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Azure login (publish profile)
        uses: azure/login@v2
        with:
          auth-type: 'publish-profile'
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      # opcional: setar app settings no Azure
      - name: Ensure App Settings on Azure
        uses: azure/appservice-settings@v1
        with:
          app-name: 'surebeteiro-web'
          app-settings-json: >
            [
              {"name":"NEXT_PUBLIC_SUPABASE_URL","value":"${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}","slotSetting":false},
              {"name":"NEXT_PUBLIC_SUPABASE_ANON_KEY","value":"${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}","slotSetting":false},
              {"name":"NEXT_PUBLIC_SITE_URL","value":"${{ secrets.NEXT_PUBLIC_SITE_URL }}","slotSetting":false}
            ]

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'surebeteiro-web'
          # 👇 publica a pasta do projeto
          package: ./project
