# .github/workflows/azure-webapps-node.yml
name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (CI)
        run: npm ci

      - name: Build
        run: npm run build

      # ✅ LOGIN CORRETO COM PUBLISH PROFILE
      - name: Azure login (publish profile)
        uses: azure/login@v2
        with:
          auth-type: 'publish-profile'
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      # Opcional: configurar app settings
      - name: Ensure App Settings on Azure
        uses: azure/appservice-settings@v1
        with:
          app-name: 'surebeteiro-web'
          app-settings-json: >
            [
              {"name":"NEXT_PUBLIC_SUPABASE_URL","value":"${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}","slotSetting":false},
              {"name":"NEXT_PUBLIC_SUPABASE_ANON_KEY","value":"${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}","slotSetting":false},
              {"name":"NEXT_PUBLIC_SITE_URL","value":"${{ secrets.NEXT_PUBLIC_SITE_URL }}","slotSetting":false}
            ]

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'surebeteiro-web'
          package: .
